# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'RottenTomatoes' do
platform:ios,"7.0"
pod 'AFNetworking'
end

target 'RottenTomatoesTests' do

end

